[general]
  genericTimezone = "Asia/Shanghai"
  timezone = "Asia/Shanghai"
  logLevel = "verbose"
  encryptionKey = "SeU@j5bpw!7WoxAp"
  executionsDataPrune = true
  executionsDataMaxAge = 72
  executionsDataSaveOnSuccess = "none"
  executionsDataSaveOnError = "all"
  executionsDataSaveOnProgress = false
  executionsDataSaveManualExecutions = false

[server]
  protocol = "http"
  host = "0.0.0.0"
  port = 5678
  baseUrl = "/"

[database]
  type = "postgres"
  host = "containers-us-west-156.railway.app"
  port = 6676
  database = "railway"
  schema = "public"
  user = "postgres"
  password = "JFYW6034H4UY3By84Lhl"

[security]
  strategy = "basicAuth"
  user = "liangmingxin"
  password = "liangmingxin"
